### Listar filmes
GET http://localhost:3001

### Buscar filmes
GET http://localhost:3001/A Proposta

### Adicionar aos favoritos
POST  http://localhost:3001/favoritos/titulo
Content-Type: application/json

{
    "titulo" : "O Banqueiro"
}

# {
#     "titulo": "A Proposta"
# }

### Deletar
DELETE http://localhost:3001/titulo

### Deletar dos favoritos
# DELETE http://localhost:3000/2/A Proposta

### Cadastrar filme
POST http://localhost:3001/filme
Content-Type: application/json


# {
#     "titulo": "A Proposta",
#     "genero": "Comédia Romântica",
#     "ano": 2009
# }

{
   "titulo": "Garota Mimada",
   "genero": "Comédia Romântica",
   "ano": 2008
}

# {

    #"titulo": "Viagem 2: A Ilha Misteriosa",
    #"genero": "Ficção Científica",
    #"ano": 2012
    
# }



   